### ISSUE TITLE
[HCMC] Web Developer - Cong ty Knightsbridge Vietnam

### ISSUE THREAD

**Issue by ngandxt** [phpvietnam/jobs#3]
Chào các bạn, hiện tại công ty Knighsbridge Việt Nam (công ty chuyên về online marketing cần tuyển 01 vị trí lập trình web với chi tiết như sau. Các bạn quan tâm vui lòng gửi CV tiếng Anh mới nhất qua email: ngan.dang@knightsbridgevn.com
### Job Description

The Web Developer will be responsible for:
- Responsible for developing website page: programming, designing, coding and modifying websites, from layout to function.
- Create visually appealing sites that feature user-friendly design and clear navigation.
- Creation of site layout/user interface from provided design concepts by using standard HTML/CSS practices
- Routine daily update & maintenance of existing sites and applications
### Job Requirement
- University graduated.
- Have a strong understanding of UI, cross-browser compatibility, general web functions and standards.
  Deep expertise and hands on experience with Web Applications and programming languages such as HTML, HTML5, CSS, CSS3, JavaScript, JQuery, API's, ASP.Net, C#, and T-SQL.
- Deep functional knowledge or hands on design experience with Web Services (REST, SOAP, etc. ...).
- Understanding the benefits of SEO and the development skills to support SEO are a plus.
- Creative, imaginative, open-minded, and dynamic.
- Having experience in Responsive Layout website, FLASH banner, collection - Intro, Mini site, landing page event and others relating to website.
- Fairly good English communication (writing and reading).
- Ability to work under pressure with positive attitude towards tight deadlines.
- Good team player.
- Attention to detail.

**Comment by and1truong** [comment]
Không có địa chỉ sao bạn Ngân (:

**Comment by ngandxt** [comment]
Hi Andy,

Địa chỉ công ty ở số 2 Ngô Đức Kế, Q1, tòa nhà Mê Linh  Point nhé anh.

Ngân
